"""update user table

Revision ID: 8f24ddbad40a
Revises: 6ea830e970c2
Create Date: 2024-06-26 14:31:21.773279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f24ddbad40a"
down_revision: Union[str, None] = "6ea830e970c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active")
    # ### end Alembic commands ###
