"""rename category in category_name in categories table

Revision ID: 6ea830e970c2
Revises: 472632e5a2d4
Create Date: 2024-06-20 16:38:04.113583

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6ea830e970c2"
down_revision: Union[str, None] = "472632e5a2d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("category_name", sa.VARCHAR(length=100), nullable=False),
    )
    op.drop_column("categories", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("category", mysql.VARCHAR(length=100), nullable=False),
    )
    op.drop_column("categories", "category_name")
    # ### end Alembic commands ###
